### PR TITLE
Publish multi-arch images with GitHub Actions

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Currently, only images for amd64 and arm (32-bit) are published. This PR changes the workflow to publish images for arm64 too, using the same Dockerfile.

Additionally, it also publishes images to GitHub Container Registry. This is better for a lot of people because Docker Hub is severely rate-limiting pulls to non-official repos, and it's especially bad for users behind a CG-NAT (like me :( ).

The workflow runs on master/main (publishing images tagged `edge`) and on tags that start with `v`, publishing images tagged `latest` and `<version>` (e.g. `0.4.5`). The images are all multi-arch, so the same tag works on all architectures.

For this to work, you'll need to set 3 secrets for Actions:

- CR_PAT: A GitHub Personal Access Token with access to packages (with `write:packages` scope)
- DOCKER_USERNAME and DOCKER_PASSWORD: for Docker Hub

Hope this helps :)

### CODE REVIEW

**Comment by TheConnMan** [comment]
Wow, thank you! This supersedes #29, correct? I'm happy to use GitHub actions if it means I don't have to convert to Circle CI.

How could I go about testing this? If it's a standard GitHub action that I load up with my Docker Hub credentials then I can give it a shot.

**Comment by ItalyPaleAle** [comment]
Yes it would! Actions is free.

> How could I go about testing this? If it's a standard GitHub action that I load up with my Docker Hub credentials then I can give it a shot.

Correct. You will need to set the 3 secrets above in the repo's settings (as secrets for Actions). Two are the Docker Hub username and password. The third is the personal access token for GitHub with permission to access packages. Then, merge it and it will run. Every commit to the main branch will publish an image with tag "edge", while releases require a Git tag starting with "v"

I have tested this on my fork and seemed to be working fine, but it may take a run or two for this to work fine here too.

**Comment by TheConnMan** [comment]
@ItalyPaleAle wonderful. I've added two secrets, but need a GitHub action before I can add the last one and test.

Either way, I normally use `latest-dev` instead of `edge` (same concept), though I build it off the `dev` branch. Please verify the changes I just pushed to this PR.

If those look good, I'll merge this to dev, see the action get created, add the last env var, make sure it all works for dev, then roll it into the main branch!

**Comment by ItalyPaleAle** [comment]
If you want to build from `dev` only and not `main/master`, maybe remove these lines? https://github.com/TheConnMan/docker-hub-rss/pull/44/files#diff-7af0deaa3194691fba56e1987aff37e4328626c22589bef1f20bbbe24d516b9aR6-R7

Otherwise, your changes make sense and LGTM

**Comment by TheConnMan** [comment]
Thanks. I want to build `latest-dev` off the `dev` branch and build the `latest` and versioned images off `master`, as you had it. I'll test this out later today.

**Comment by TheConnMan** [comment]
Well myyyyyyyy goodness. I think it actually worked! @ItalyPaleAle can you double-check https://github.com/TheConnMan/docker-hub-rss/pkgs/container/docker-hub-rss and https://hub.docker.com/r/theconnman/docker-hub-rss/tags to confirm we're looking good?

**Comment by ItalyPaleAle** [comment]
Sorry @TheConnMan I'm on vacation right now and can't test right now :( But it _seems_ to be working fine :)

**Comment by TheConnMan** [comment]
Awesome. I'll give it another once-over this weekend then cut a versioned release. Thanks again for your help!

**Comment by ItalyPaleAle** [comment]
@TheConnMan  do you think you could cut a release please?

**Comment by TheConnMan** [comment]
Released! Thanks for the bump here.

**Pull request merged**
