### PR TITLE
Add an info endpoint with version information

### PR DESCRIPTION
**Pull request by TheConnMan**
Ref #48

### CODE REVIEW

**Comment by mortee** [comment]
Does the app have any other "state" besides its own version, and maybe node.js, OS etc version? And honestly I would consider even exposing the latter two publicly as unnecessary security exposure.

**Comment by TheConnMan** [comment]
I agree on leaving out Node and OS information. Nothing else comes to mind. I'll merge this and cut a new version of the project.

**Comment by ItalyPaleAle** [comment]
If you're interested in exposing more info, something else that could (possibly) be useful would be to have `/metrics` endpoint, for example exposing Prometheus-compatible metrics.

Example: https://blog.risingstack.com/node-js-performance-monitoring-with-prometheus/

**Comment by TheConnMan** [comment]
@ItalyPaleAle good idea. I'm a bit nervous about putting this on the same public port. It may make sense to put on a private endpoint that can be exposed separately.

**Comment by ItalyPaleAle** [comment]
Yes, that would be great

**Pull request merged**
